#!/bin/bash

# 实验结果已保存到本地 Git 仓库
# 要 推送到 obsidian, 请配置认证

echo "当前问题："
echo "- Git credential store 未配置"
echo "- VS Code Git 扩展的 socket (/run/user/0/vscode-git-547d1d4cf6.sock) 不存在"
echo "- 没有 SSH keys"
echo ""
echo "解决方案："
echo ""
echo "方案 1: 使用 GitHub Personal Access Token (推荐)"
echo "---------------------------------------------------"
echo "1. 创建 token: https://github.com/settings/tokens/new"
echo "   - 选择权限: repo (full control)"
echo "   - 复制生成的 token"
echo ""
echo "2. 推送命令:"
echo "export GITHUB_TOKEN='ghp_YOUR_TOKEN_HERE'"
echo ""
echo "cd /tmp"
echo "git clone https://\$GITHUB_TOKEN@github.com/kakushuu/obsidian.git obsidian-lab"
echo "cd obsidian-lab"
echo "mkdir -p lab/2026-03-17-trajectory-innovation-experiments/{logs,results}"
echo ""
echo "# 复制实验文件"
echo "cp /home/research/Agri-MBT/experiments/EXPERIMENT_SUMMARY_2026-03-17.md lab/2026-03-17-trajectory-innovation-experiments/"
echo "cp /home/research/Agri-MBT/experiments/*.log lab/2026-03-17-trajectory-innovation-experiments/logs/"
echo "cp /home/research/Agri-MBT/experiments/*.json lab/2026-03-17-trajectory-innovation-experiments/results/"
echo ""
echo "# 提交并推送"
echo "git add ."
echo "git commit -m 'Add trajectory innovation experiments (all failed)'"
echo "git push origin main"
echo ""
echo "方案 2: 重新打开 VS Code (临时)"
echo "----------------------------------------"
echo "重新打开 VS Code 窗口， VS Code Git 扩展会重新启动并恢复认证"
echo ""
echo "方案 3: 配置 SSH (如果需要)"
echo "---------------------------------"
echo "ssh-keygen -t ed25519 -C 'your_email@example.com'"
echo "cat ~/.ssh/id_ed25519.pub"
echo "# 将公钥添加到 GitHub: https://github.com/settings/ssh/new"
